### ISSUE TITLE
Authorization cancel does nothing

### ISSUE THREAD

**Issue by schanzen** [reclaimID/ui#2]
If the user cancels the authorization process, simply reset by redirecting to https://ui.reclaim.

**Comment by kiliant** [comment]
is this really intended? shouldn't the user be redirected back to the source of the request?

**Comment by schanzen** [comment]
You are right: https://tools.ietf.org/html/rfc6749#section-4.2.2.1
The ui or API should redirect as defined in the spec.

**Comment by schanzen** [comment]
Suggestion:
1. We add a reject rest API to our OpenID Connect plugin in GNUnet
2. This API sets a magic cookie that allows the authorize endpoint to identify the rejected authorization
3. We add a reject() function to open-id.service.ts that first calls the reject API and then redirects to the authorize endpoint (analog to the login() function in the service)
4. The authorize endpoint must consume the cookie and initiate a redirect to the redirect_uri with an error description.

**Comment by schanzen** [comment]
The above approach allows us to convert the verbose redirect URI top-level domain to a human readable format (instead of the PKEY) inside the plugin.

**Comment by schanzen** [comment]
Added logic to plugin in GNUnet upstream and changed UI to use new API in commit 6e99bf74fef7af9b5c350a7cf828be955f501181
